name: orphi-crowdfund
services:
- name: web
  source_dir: /
  github:
    repo: timecapsulellc/orphicrowdfund
    branch: deployment
  run_command: npm run start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_SUPABASE_URL
    value: ${VITE_SUPABASE_URL}
    type: SECRET
  - key: VITE_SUPABASE_ANON_KEY
    value: ${VITE_SUPABASE_ANON_KEY}
    type: SECRET 