name: leadfive-production
services:
- name: web
  source_dir: /
  github:
    repo: timecapsulellc/leadfive
    branch: main
  run_command: npm run start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_CONTRACT_ADDRESS
    value: 0x86CCF0eb67a7aB09234d5F4aE265F9eFB8E8fb6c
  - key: VITE_NETWORK_ID
    value: "56"
  - key: VITE_WEB3_PROVIDER_URL
    value: https://bsc-dataseed.binance.org/
    type: SECRET
  - key: VITE_SUPABASE_ANON_KEY
    value: ${VITE_SUPABASE_ANON_KEY}
    type: SECRET 