name: leadfive
region: nyc
services:
- name: leadfive-web
  type: static_site
  source_dir: /
  github:
    repo: timecapsulellc/leadfive
    branch: main
    deploy_on_push: true
  build_command: bash build.sh
  output_dir: dist
  routes:
  - path: /
    preserve_path_prefix: false
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_APP_ENV
    value: production
  - key: VITE_CONTRACT_ADDRESS
    value: "0x29dcCb502D10C042BcC6a02a7762C49595A9E498"
  - key: VITE_NETWORK_ID
    value: "56"
  - key: VITE_WEB3_PROVIDER_URL
    value: "https://bsc-dataseed.binance.org/"
  - key: VITE_DEBUG_MODE
    value: "false"
  - key: VITE_CHAIN_ID
    value: "56"
  - key: VITE_NETWORK_NAME
    value: "BSC Mainnet"
  - key: VITE_RPC_URL
    value: "https://bsc-dataseed.binance.org/"
  - key: VITE_EXPLORER_URL
    value: "https://bscscan.com"
  - key: VITE_USDT_ADDRESS
    value: "0x55d398326f99059fF775485246999027B3197955"
  - key: VITE_WEBSOCKET_URL
    value: "wss://ws.leadfive.today"
  - key: VITE_WEBSOCKET_HOST
    value: "ws.leadfive.today"
  - key: VITE_WEBSOCKET_PORT
    value: "443"
  - key: VITE_API_BASE_URL
    value: "https://api.leadfive.today"
  - key: VITE_ETHEREUM_RPC_URL
    value: "https://eth-mainnet.g.alchemy.com/v2/demo"
  - key: VITE_POLYGON_RPC_URL
    value: "https://polygon-rpc.com"
  - key: VITE_OWNER_ADDRESS
    value: "0xDf628ed21f0B27197Ad02fc29EbF4417C04c4D29"
  - key: VITE_ADMIN_ADDRESS
    value: "0xDf628ed21f0B27197Ad02fc29EbF4417C04c4D29"
  - key: VITE_FEE_RECIPIENT
    value: "0xeB652c4523f3Cf615D3F3694b14E551145953aD0"
  - key: VITE_OPENAI_API_KEY
    value: "YOUR_OPENAI_API_KEY"
  - key: VITE_OPENAI_MODEL
    value: "gpt-3.5-turbo"
  - key: VITE_OPENAI_MAX_TOKENS
    value: "500"
  - key: VITE_ELEVENLABS_API_KEY
    value: "YOUR_ELEVENLABS_API_KEY"
  - key: VITE_ELEVENLABS_VOICE_ID
    value: "9PVP7ENhDskL0KYHAKtD"
  - key: VITE_ELEVENLABS_MODEL
    value: "eleven_multilingual_v2"
  - key: VITE_ELEVENLABS_AGENT_ID
    value: "YOUR_ELEVENLABS_AGENT_ID"
  - key: VITE_ENABLE_AI_SYNTHESIS
    value: "true"
  - key: VITE_MAX_FILE_SIZE
    value: "10485760"
  - key: NODE_OPTIONS
    value: "--max-old-space-size=2048"
# static.json in project root ensures SPA routing for all paths
# No further changes needed for DigitalOcean static hosting
# Optional: Add alerts
alerts:
