name: leadfive-app
services:
- name: web
  source_dir: /
  github:
    repo: leadfive/platform
    branch: main
    deploy_on_push: true
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  build_command: npm run build
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_APP_TITLE
    value: LeadFive - Revolutionary Web3 Platform
  - key: VITE_CONTRACT_ADDRESS
    value: "0x29dcCb502D10C042BcC6a02a7762C49595A9E498"
  - key: VITE_NETWORK_NAME
    value: "BSC Mainnet"
  - key: VITE_CHAIN_ID
    value: "56"
  - key: VITE_RPC_URL
    value: "https://bsc-dataseed1.binance.org/"