name: leadfive
region: nyc
services:
- name: leadfive-web
  type: static_site
  source_dir: /
  github:
    repo: timecapsulellc/LeadFive
    branch: main
    deploy_on_push: true
  build_command: bash build.sh
  output_dir: dist
  routes:
  - path: /
  - path: /register
  - path: /dashboard  
  - path: /about
  - path: /packages
  - path: /referrals
  - path: /login
  - path: /genealogy
  - path: /withdrawals
  catchall_document: index.html
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_APP_ENV
    value: production
  - key: VITE_CONTRACT_ADDRESS
    value: "0x29dcCb502D10C042BcC6a02a7762C49595A9E498"
  - key: VITE_NETWORK_ID
    value: "56"
  - key: VITE_WEB3_PROVIDER_URL
    value: "https://bsc-dataseed.binance.org/"
  - key: VITE_DEBUG_MODE
    value: "false"
  - key: VITE_CHAIN_ID
    value: "56"
  - key: VITE_NETWORK_NAME
    value: "BSC Mainnet"
  - key: VITE_RPC_URL
    value: "https://bsc-dataseed.binance.org/"
  - key: VITE_EXPLORER_URL
    value: "https://bscscan.com"
  - key: VITE_USDT_ADDRESS
    value: "0x55d398326f99059fF775485246999027B3197955"
  - key: VITE_WEBSOCKET_URL
    value: "wss://ws.leadfive.today"
  - key: VITE_WEBSOCKET_HOST
    value: "ws.leadfive.today"
  - key: VITE_WEBSOCKET_PORT
    value: "443"
  - key: VITE_API_BASE_URL
    value: "https://api.leadfive.today"
  - key: VITE_ETHEREUM_RPC_URL
    value: "https://eth-mainnet.g.alchemy.com/v2/demo"
  - key: VITE_POLYGON_RPC_URL
    value: "https://polygon-rpc.com"
  - key: VITE_OWNER_ADDRESS
    value: "0xDf628ed21f0B27197Ad02fc29EbF4417C04c4D29"
  - key: VITE_ADMIN_ADDRESS
    value: "0xDf628ed21f0B27197Ad02fc29EbF4417C04c4D29"
  - key: VITE_FEE_RECIPIENT
    value: "0xeB652c4523f3Cf615D3F3694b14E551145953aD0"
  - key: VITE_DEFAULT_REFERRAL_CODE
    value: "K9NBHT"
  - key: VITE_DEFAULT_SPONSOR
    value: "0xCeaEfDaDE5a0D574bFd5577665dC58d132995335"
  - key: VITE_TREASURY_WALLET
    value: "0xDf628ed21f0B27197Ad02fc29EbF4417C04c4D29"
  - key: VITE_ENABLE_AI_FEATURES
    value: "true"
  - key: VITE_ENABLE_PRICE_TICKER
    value: "true"
  - key: VITE_ENABLE_PORTFOLIO_TRACKING
    value: "true"
  - key: VITE_ENABLE_MARKET_WIDGETS
    value: "true"
  - key: VITE_ENABLE_AI_SYNTHESIS
    value: "true"
  - key: VITE_MAX_FILE_SIZE
    value: "10485760"
  - key: NODE_OPTIONS
    value: "--max-old-space-size=2048"
# static.json in project root ensures SPA routing for all paths
# No further changes needed for DigitalOcean static hosting
# Optional: Add alerts
alerts:
